repos:
  - repo: local
    hooks:
      - id: black
        name: black (via uv)
        entry: uv run black
        language: system
        types: [python]

      - id: flake8
        name: flake8 (via uv)
        entry: uv run flake8
        language: system
        types: [python]

      - id: isort
        name: isort (via uv)
        entry: uv run isort
        language: system
        types: [python]

      - id: mypy
        name: mypy (via uv)
        entry: uv run mypy
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]