repos:
  - repo: local
    hooks:
      - id: sort-imports
        name: Ruff sort imports (via uv)
        entry: uv run ruff check --select I --fix .
        language: system
        types: [python]

      - id: format
        name: Ruff Formatting (via uv)
        entry: uv run ruff format .
        language: system
        types: [python]

      - id: lint
        name: Ruff Linting (via uv)
        entry: uv run ruff check .
        language: system
        types: [python]

      - id: mypy
        name: mypy (via uv)
        entry: uv run mypy
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
